version: '3.8'

services:
  jimmy-ai-generator:
    image: ghcr.io/VOTRE_USERNAME/jimmy-ai-letter-generator:latest
    container_name: jimmy-ai-production
    restart: unless-stopped
    ports:
      - ""8080:80""
    environment:
      - TZ=Europe/Paris
      - APP_VERSION=3.0.0
      - AI_ENABLED=true
      - NODE_ENV=production
    volumes:
      - jimmy-userdata:/usr/share/nginx/html/data
      - jimmy-models:/usr/share/nginx/html/models
      - jimmy-logs:/var/log/nginx
    networks:
      - jimmy-network
    labels:
      - ""traefik.enable=true""
      - ""traefik.http.routers.jimmy-ai-prod.rule=Host(`candidatures.mondomaine.com`)""
      - ""traefik.http.routers.jimmy-ai-prod.tls=true""
      - ""traefik.http.routers.jimmy-ai-prod.tls.certresolver=letsencrypt""
      - ""traefik.http.services.jimmy-ai-prod.loadbalancer.server.port=80""
    healthcheck:
      test: [""CMD"", ""wget"", ""--quiet"", ""--tries=1"", ""--spider"", ""http://localhost/health""]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: ""json-file""
      options:
        max-size: ""10m""
        max-file: ""5""

networks:
  jimmy-network:
    external: true

volumes:
  jimmy-userdata:
    external: true
  jimmy-models:
    external: true  
  jimmy-logs:
    external: true
